
# sudo: false
language: node_js
node_js: 12

# 部署相关
before_deploy:
  - npm run build # 生成npm包
deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_token: "$NPM_TOKEN"
    cleanup: true # 在运行测试之后且在发行之前，Travis CI会清理所有其他文件和所做的更改， 默认false标识要清理
    on:
      tags: true
    tag: latest # 给npm包添加版本

branches:
  only:
  # - /^v\d+\.\d+(\.\d+)?(-\S*)?$/  # 只在tag分支时候才会build
  - master